### ISSUE TITLE
Don't use `{}` as a type

### ISSUE THREAD

**Issue by jmatsushita** [thought2/purescript-ts-bridge#10]
Friendly reminder about this issue I've mentioned in https://github.com/thought2/purescript-ts-bridge/issues/6 
> the @typescript-eslint/ban-types rule doesn't like the {} type, is that expected or is there a better way to encode nullary constructors as Variants with labeled-data ?

```
Don't use `{}` as a type. `{}` actually means "any non-nullish value".
- If you want a type meaning "any object", you probably want `object` instead.
- If you want a type meaning "any value", you probably want `unknown` instead.
- If you want a type meaning "empty object", you probably want `Record<string, never>` instead.
- If you really want a type meaning "any non-nullish value", you probably want `NonNullable<unknown>` instead.eslint[@typescript-eslint/ban-types](https://typescript-eslint.io/rules/ban-types)
```

**Comment by thought2** [comment]
I think we should use `Record<string, never>` for the empty record. This should be an easy fix, I can do this in the next days.

**Comment by thought2** [comment]
Here's a PR:
https://github.com/thought2/purescript-ts-bridge/pull/11
