### ISSUE TITLE
KindsDoNotUnify because of `VariantEncFlat` upstream name change

### ISSUE THREAD

**Issue by jmatsushita** [thought2/purescript-ts-bridge#7]
This [commit](https://github.com/thought2/purescript-variant-encodings/commit/a4ad3a69e3f1fa6a50d511ae9035ca49c04f36ae) changes the name of the `VariantEncFlat` type. 

```bash
 [1/1 KindsDoNotUnify] .spago/ts-bridge/main/src/TsBridge/DefaultImpls.purs:298:65

298    tsBridgeVariantEncFlat :: tok -> Proxy (VariantEncFlat symTag r) -> TsBridgeM DTS.TsType
```

In addition to a fix, it might be good to [pin the version in the `packages.dhall`](https://github.com/thought2/purescript-ts-bridge/blob/main/packages.dhall#L13) ?

**Comment by thought2** [comment]
Is this still the case? I have updated everything.

**Comment by jmatsushita** [comment]
It works now, thank you!
